In [1]:
import numpy as np
from scipy.linalg import svd

In [2]:
A = np.array([[7,3,2],[2,3,-2]])
A

array([[ 7,  3,  2],
       [ 2,  3, -2]])

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
A = StandardScaler().fit_transform(A)

In [6]:
A

array([[ 1.,  0.,  1.],
       [-1.,  0., -1.]])

In [9]:
#Covariance matrix
C = A.dot(A.T) / len(A[0])
C

array([[ 0.66666667, -0.66666667],
       [-0.66666667,  0.66666667]])

In [10]:
val, vec = np.linalg.eig(C)
print('Eigenvalues:\n', val)
print('\nEigenvectors:\n', vec)

Eigenvalues:
 [1.33333333 0.        ]

Eigenvectors:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


Singular Vector Decompostition

In [11]:
U, S, V_T = svd(A)

In [13]:
print('U:\n',U)
print('\nSingular Values:\n',S)
print('\nEigenValues:\n',S*S/len(A[0]))
print('\nV_T:\n',V_T)

U:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Singular Values:
 [2.00000000e+00 1.43493693e-17]

EigenValues:
 [1.33333333e+00 6.86348000e-35]

V_T:
 [[ 0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]]
